export const COLORS = {
  bg: '#0A0A0A',
  bg2: '#1A1A1A',
  surface: '#1E1E1E',
  surface2: '#2A2A2A',
  surface3: '#333333',
  gold: '#D4A017',
  goldBright: '#F0C040',
  goldMuted: 'rgba(212,160,23,0.15)',
  text: '#F5F5F0',
  textSecondary: '#A0A0A0',
  textTertiary: '#606060',
  green: '#3DBE6C',
  red: '#E84040',
  blue: '#4A90D9',
  border: 'rgba(255,255,255,0.08)',
  border2: 'rgba(212,160,23,0.3)',
};

export const KONG_MSGS = [
  "Kong doesn't skip leg day. Neither should you. 🦍",
  "Pain is temporary. Gains are forever. 💪",
  "Every rep is a rep closer to your best self. ⚡",
  "The iron never lies. Show up. 🏋️",
  "Weak excuses build weak bodies. 🔥",
  "Kong approves of your dedication. 🦍👑",
  "Rest is part of the program. Recover like a beast. 😤",
  "Your only competition is yesterday's you. 🎯",
  "The bar doesn't care about your feelings. 🏋️",
  "Champions are made when nobody is watching. 👑",
  "One more rep. Always one more rep. 💀",
  "Sweat is just fat crying. 🔥",
];

export const AVATARS = [
  '🦍','💪','🏋️','🔥','⚡','🦁','🐺','🦅',
  '🐉','👑','💀','🤖','🦊','🐻','🦈','🐯',
  '🦏','🦬','🐗','🦌','🦝','🦨','🦡','🦦',
  '🐆','🐅','🦓','🦒','🐘','🦛','🦏','🐪',
  '🧠','💎','🌟','⚔️','🛡️','🎯','🏆','🎖️',
];

export const DIET_TYPES = [
  { name: 'Balanced', emoji: '⚖️' },
  { name: 'Keto', emoji: '🥩' },
  { name: 'Mediterranean', emoji: '🫒' },
  { name: 'Carnivore', emoji: '🥩' },
  { name: 'Vegan', emoji: '🌱' },
  { name: 'Paleo', emoji: '🦴' },
  { name: 'IIFYM', emoji: '📊' },
  { name: 'Fasting', emoji: '⏰' },
];

export const RANKS = [
  { name: 'Dormant', emoji: '🪨', minXP: 0, color: '#6B7280', tagline: 'Your journey begins. Most never start.' },
  { name: 'Awakening', emoji: '🌱', minXP: 500, color: '#10B981', tagline: 'The body is listening. Keep going.' },
  { name: 'Rising', emoji: '🔥', minXP: 1500, color: '#F59E0B', tagline: 'Momentum is building. You feel it.' },
  { name: 'Forged', emoji: '⚡', minXP: 3500, color: '#3B82F6', tagline: 'Discipline is becoming identity.' },
  { name: 'Ascendant', emoji: '🦅', minXP: 7000, color: '#8B5CF6', tagline: 'You operate at a level most cannot see.' },
  { name: 'Sovereign', emoji: '👑', minXP: 15000, color: '#F59E0B', tagline: 'Rare. Optimized. Unstoppable.' },
  { name: 'Transcendent', emoji: '✨', minXP: 30000, color: '#FFFFFF', tagline: 'You have become the standard.' },
];

export const SPLITS = [
  {
    id: 'ppl6',
    name: 'PPL 6-Day',
    emoji: '🔄',
    daysPerWeek: 6,
    description: 'Push/Pull/Legs × 2 — the classic hypertrophy split',
    days: [
      { name: 'Monday — Push', exercises: ['Bench Press', 'Overhead Press', 'Incline DB Press', 'Lateral Raises', 'Tricep Pushdowns', 'Skull Crushers'] },
      { name: 'Tuesday — Pull', exercises: ['Deadlift', 'Barbell Rows', 'Pull-ups', 'Face Pulls', 'Barbell Curls', 'Hammer Curls'] },
      { name: 'Wednesday — Legs', exercises: ['Squat', 'Romanian Deadlift', 'Leg Press', 'Leg Curls', 'Calf Raises', 'Leg Extensions'] },
      { name: 'Thursday — Push', exercises: ['Overhead Press', 'Incline Bench', 'Cable Flyes', 'Lateral Raises', 'Tricep Dips', 'Overhead Tricep Extension'] },
      { name: 'Friday — Pull', exercises: ['Rack Pulls', 'Seated Cable Rows', 'Lat Pulldowns', 'Rear Delt Flyes', 'Preacher Curls', 'Cable Curls'] },
      { name: 'Saturday — Legs', exercises: ['Front Squat', 'Hack Squat', 'Walking Lunges', 'Leg Curls', 'Standing Calf Raises', 'Glute Bridges'] },
    ],
  },
  {
    id: 'ul4',
    name: 'Upper/Lower 4-Day',
    emoji: '⬆️⬇️',
    daysPerWeek: 4,
    description: 'Balanced upper/lower split for strength and size',
    days: [
      { name: 'Monday — Upper', exercises: ['Bench Press', 'Barbell Rows', 'Overhead Press', 'Pull-ups', 'Barbell Curls', 'Tricep Pushdowns'] },
      { name: 'Tuesday — Lower', exercises: ['Squat', 'Romanian Deadlift', 'Leg Press', 'Leg Curls', 'Calf Raises'] },
      { name: 'Thursday — Upper', exercises: ['Incline Bench', 'Seated Cable Rows', 'DB Shoulder Press', 'Lat Pulldowns', 'Hammer Curls', 'Skull Crushers'] },
      { name: 'Friday — Lower', exercises: ['Deadlift', 'Front Squat', 'Walking Lunges', 'Leg Extensions', 'Seated Calf Raises'] },
    ],
  },
  {
    id: 'bro5',
    name: 'Bro Split 5-Day',
    emoji: '💪',
    daysPerWeek: 5,
    description: 'Classic bodybuilder split — one muscle group per day',
    days: [
      { name: 'Monday — Chest', exercises: ['Bench Press', 'Incline Bench', 'Decline Bench', 'Cable Flyes', 'Dips', 'Push-ups'] },
      { name: 'Tuesday — Back', exercises: ['Deadlift', 'Barbell Rows', 'Pull-ups', 'Lat Pulldowns', 'Seated Cable Rows', 'Face Pulls'] },
      { name: 'Wednesday — Shoulders', exercises: ['Overhead Press', 'Lateral Raises', 'Front Raises', 'Rear Delt Flyes', 'Shrugs', 'Arnold Press'] },
      { name: 'Thursday — Arms', exercises: ['Barbell Curls', 'Hammer Curls', 'Preacher Curls', 'Tricep Pushdowns', 'Skull Crushers', 'Dips'] },
      { name: 'Friday — Legs', exercises: ['Squat', 'Leg Press', 'Romanian Deadlift', 'Leg Curls', 'Leg Extensions', 'Calf Raises'] },
    ],
  },
  {
    id: 'fb3',
    name: 'Full Body 3-Day',
    emoji: '🏋️',
    daysPerWeek: 3,
    description: 'Full body compound movements — great for beginners',
    days: [
      { name: 'Monday — Full Body A', exercises: ['Squat', 'Bench Press', 'Barbell Rows', 'Overhead Press', 'Deadlift'] },
      { name: 'Wednesday — Full Body B', exercises: ['Front Squat', 'Incline Bench', 'Pull-ups', 'DB Shoulder Press', 'Romanian Deadlift'] },
      { name: 'Friday — Full Body C', exercises: ['Deadlift', 'Dips', 'Barbell Rows', 'Squat', 'Overhead Press'] },
    ],
  },
  {
    id: 'hit3',
    name: 'HIT Mentzer',
    emoji: '💥',
    daysPerWeek: 3,
    description: 'High Intensity Training — 1-2 sets to absolute failure',
    days: [
      { name: 'Monday — Chest/Back', exercises: ['Bench Press (1 set to failure)', 'Incline Press (1 set to failure)', 'Deadlift (1 set to failure)', 'Pull-ups (1 set to failure)'] },
      { name: 'Wednesday — Legs', exercises: ['Squat (1 set to failure)', 'Leg Press (1 set to failure)', 'Leg Curls (1 set to failure)', 'Calf Raises (1 set to failure)'] },
      { name: 'Friday — Shoulders/Arms', exercises: ['Overhead Press (1 set to failure)', 'Lateral Raises (1 set to failure)', 'Barbell Curls (1 set to failure)', 'Tricep Pushdowns (1 set to failure)'] },
    ],
  },
  {
    id: 'kb4',
    name: 'Kettlebell',
    emoji: '🔔',
    daysPerWeek: 4,
    description: 'Full body kettlebell program for strength and conditioning',
    days: [
      { name: 'Monday — Strength', exercises: ['KB Swings 5×10', 'KB Goblet Squat 4×12', 'KB Press 4×8', 'KB Row 4×10', 'KB Deadlift 3×8'] },
      { name: 'Tuesday — Conditioning', exercises: ['KB Snatch 5×5 each', 'KB Clean & Press 4×6', 'KB Turkish Get-Up 3×3 each', 'KB Windmill 3×5 each'] },
      { name: 'Thursday — Strength', exercises: ['KB Double Swing 5×8', 'KB Front Squat 4×10', 'KB Push Press 4×8', 'KB Bent Row 4×10'] },
      { name: 'Friday — Conditioning', exercises: ['KB Complex: Swing+Clean+Press 4×5', 'KB Farmer Carry 4×40m', 'KB Renegade Row 3×8', 'KB Halo 3×10'] },
    ],
  },
];

export const FAMOUS_WODS = [
  {
    id: 'murph',
    name: 'Murph',
    emoji: '🏃',
    category: 'famous',
    xp: 200,
    description: '1 mile run, 100 pull-ups, 200 push-ups, 300 squats, 1 mile run',
    details: 'For time. Partition the pull-ups, push-ups, and squats as needed. Start and finish with a 1 mile run. If you have a 20 lb vest or body armor, wear it.',
    time: 'For Time',
  },
  {
    id: 'cindy',
    name: 'Cindy',
    emoji: '🔄',
    category: 'famous',
    xp: 100,
    description: '20 min AMRAP: 5 pull-ups, 10 push-ups, 15 squats',
    details: 'As Many Rounds As Possible in 20 minutes. Score is total rounds completed.',
    time: '20 min AMRAP',
  },
  {
    id: 'fran',
    name: 'Fran',
    emoji: '⚡',
    category: 'famous',
    xp: 150,
    description: '21-15-9: Thrusters (95/65 lb) + Pull-ups',
    details: 'For time. Complete 21 thrusters and 21 pull-ups, then 15 and 15, then 9 and 9.',
    time: 'For Time',
  },
  {
    id: 'the300',
    name: 'The 300',
    emoji: '🛡️',
    category: 'famous',
    xp: 175,
    description: '300 reps total: 25 pull-ups, 50 deadlifts, 50 push-ups, 50 box jumps, 50 floor wipers, 25 clean & press, 50 pull-ups',
    details: 'For time. This is the workout used to train the cast of the movie 300.',
    time: 'For Time',
  },
  {
    id: 'angie',
    name: 'Angie',
    emoji: '💪',
    category: 'famous',
    xp: 150,
    description: '100 pull-ups, 100 push-ups, 100 sit-ups, 100 squats',
    details: 'For time. Complete all reps of each exercise before moving to the next.',
    time: 'For Time',
  },
  {
    id: 'helen',
    name: 'Helen',
    emoji: '🏃',
    category: 'famous',
    xp: 125,
    description: '3 rounds: 400m run, 21 KB swings (53/35 lb), 12 pull-ups',
    details: 'For time. Three rounds of a 400 meter run, 21 kettlebell swings, and 12 pull-ups.',
    time: 'For Time',
  },
];

export const HOLIDAY_WODS = [
  {
    id: 'turkey',
    name: 'Turkey Trot',
    emoji: '🦃',
    category: 'holiday',
    xp: 125,
    description: 'Thanksgiving special: 5k run + 50 burpees',
    details: 'Run a 5k (3.1 miles), then complete 50 burpees for time. Earn your feast!',
    time: 'For Time',
  },
  {
    id: 'xmas12',
    name: '12 Days of Xmas',
    emoji: '🎄',
    category: 'holiday',
    xp: 150,
    description: '12 exercises, cumulative reps (1+2+3...+12)',
    details: 'Day 1: 1 burpee. Day 2: 2 pull-ups + 1 burpee. Continue adding exercises through Day 12.',
    time: 'For Time',
  },
  {
    id: 'nye',
    name: 'NYE Countdown',
    emoji: '⏰',
    category: 'holiday',
    xp: 100,
    description: '31 reps of 10 exercises — ring in the new year',
    details: '31 squats, 31 push-ups, 31 sit-ups, 31 lunges, 31 burpees, 31 mountain climbers, 31 jumping jacks, 31 dips, 31 crunches, 31 plank seconds.',
    time: 'For Time',
  },
  {
    id: 'vday',
    name: "Valentine's Day",
    emoji: '💕',
    category: 'holiday',
    xp: 100,
    description: 'Partner WOD — 14 min AMRAP',
    details: 'With a partner: AMRAP in 14 minutes of 14 partner push-ups, 14 synchro squats, 14 partner sit-ups. One works, one rests.',
    time: '14 min AMRAP',
  },
  {
    id: 'july4',
    name: 'July 4th',
    emoji: '🇺🇸',
    category: 'holiday',
    xp: 250,
    description: '1776 total reps challenge',
    details: '1776 total reps: 400 squats, 300 push-ups, 276 sit-ups, 200 lunges, 176 burpees, 176 pull-ups, 176 box jumps, 76 clean & press.',
    time: 'For Time',
  },
  {
    id: 'halloween',
    name: 'Halloween',
    emoji: '🎃',
    category: 'holiday',
    xp: 130,
    description: '31 reps of 13 spooky exercises',
    details: '31 reps each: Zombie walks, Frankenstein kicks, Spider-man push-ups, Witch squats, Ghost jumps, Skeleton rows, Vampire lunges, Werewolf burpees, Mummy sit-ups, Pumpkin press, Bat wings, Cauldron swings, Monster slams.',
    time: 'For Time',
  },
  {
    id: 'murphmem',
    name: 'Memorial Day Murph',
    emoji: '🎖️',
    category: 'holiday',
    xp: 250,
    description: 'Full Murph with 20 lb vest — honor the fallen',
    details: 'Wear a 20 lb vest: 1 mile run, 100 pull-ups, 200 push-ups, 300 squats, 1 mile run. In memory of Lt. Michael Murphy.',
    time: 'For Time',
  },
  {
    id: 'shamrock',
    name: 'Shamrock Shuffle',
    emoji: '☘️',
    category: 'holiday',
    xp: 110,
    description: "St. Patrick's Day — 17 min AMRAP",
    details: '17 minute AMRAP: 17 KB swings, 17 box jumps, 17 push-ups, 17 sit-ups. Score is total rounds + reps.',
    time: '17 min AMRAP',
  },
];

export const FAKE_LEADERBOARD = [
  { name: 'IronKing_88', avatar: '👑', xp: 16200, rank: 'Sovereign' },
  { name: 'GainzGod', avatar: '🦍', xp: 8100, rank: 'Ascendant' },
  { name: 'SteelPhoenix', avatar: '🔥', xp: 4800, rank: 'Forged' },
  { name: 'BarbellBeast', avatar: '💪', xp: 2900, rank: 'Rising' },
  { name: 'IronMaiden_X', avatar: '⚡', xp: 1400, rank: 'Awakening' },
];

export const FAKE_FRIENDS = [
  { name: 'BroScience_Bob', avatar: '🐺', xp: 850, rank: 'Awakening' },
  { name: 'SwoleSister', avatar: '🦅', xp: 620, rank: 'Awakening' },
  { name: 'DeadliftDave', avatar: '🏋️', xp: 1100, rank: 'Awakening' },
  { name: 'CardioCarla', avatar: '🌊', xp: 340, rank: 'Dormant' },
  { name: 'PlatesMcGee', avatar: '🛡️', xp: 1500, rank: 'Rising' },
];

export const STARTER_TEAMS = [
  { id: 'iron', name: 'Iron Brotherhood', emoji: '🦁', color: '#E84040', members: 1247 },
  { id: 'apex', name: 'Apex Predators', emoji: '🦅', color: '#4A90D9', members: 983 },
  { id: 'silent', name: 'Silent Grind', emoji: '💀', color: '#606060', members: 756 },
  { id: 'cardio', name: 'Cardio Club', emoji: '🌊', color: '#3DBE6C', members: 2104 },
];

export const CHALLENGES = [
  { id: 'streak7', name: '7-Day Streak', emoji: '🔥', xp: 100, description: 'Work out 7 days in a row' },
  { id: 'push100', name: '100 Pushups', emoji: '💪', xp: 75, description: 'Complete 100 push-ups in one session' },
  { id: 'murph', name: 'Complete Murph', emoji: '🏃', xp: 200, description: 'Finish the Murph WOD' },
  { id: 'prweek', name: 'PR Week', emoji: '🏆', xp: 150, description: 'Set a new PR on any lift' },
  { id: 'total1k', name: '1,000 lb Total', emoji: '🏋️', xp: 250, description: 'Squat + Bench + Deadlift = 1000 lbs' },
];
